Feature/#64 todo edit
saveme-cadet/LMS-Frontend pull request #73
Opened 2022-06-28 08:12 UTC by luckylooky2

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)

- [ ] 기능 추가
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)

- Todo Page에서 각 Todo를 수정할 수 있는 기능 추가

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)

- Edit 버튼을 통해서 Todo List를 수정할 수 있는 기능을 추가합니다.
- 오늘 날짜가 아닌 경우, 글자를 모두 회색으로 변경했습니다.
- removeTodo 함수에 있었던 불필요한 변수, 로직을 삭제했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

- 이벤트 위임이라는 개념을 활용해, 여러 개의 태그에서 동일한 이벤트를 동작시킬 수 있음을 배웠습니다.

<br />

## :: 기타 질문 및 특이 사항

-

2022-06-28 11:18 UTC, mike2ox reviewed
고생하셨습니다. 전반적으로 기본 tag가 아니라 styled component로 바꿔주시면 좋을 거 같아요.

2022-06-28 11:18 UTC, mike2ox commented on src/Pages/TodoPage/CadetListItem.jsx
> +};
처음부터 styled component로 만들어 주시면 좋을거 같아요.
2차 스프린트 초반때처럼 리팩토링 styled로 바꿔주는 시간을 절약할 수 있어요.

2022-06-28 11:18 UTC, mike2ox commented on src/Pages/TodoPage/CadetListItem.jsx
>      </span>
span에 span을 다시 wrap한 이유가 있을가요

2022-06-29 14:00 UTC, GulSam00 requested changes
수고하셨습니다. 확인 부탁드립니다.

2022-06-29 14:00 UTC, GulSam00 commented on src/Pages/TodoPage/CancelButton.jsx
> +    >
함수에 인자를 전달할 필요가 없다면 굳이 화살표 함수를 쓰지 않아 주어도 되고 일반적인 콜백함수로 사용하면 됩니다.

2022-06-29 14:00 UTC, GulSam00 commented on src/Pages/TodoPage/MyTodoList.jsx
>    const [othersToDo, setOthersToDo] = useState([]);
vscode로 확인해보니 othersToDo가 사용되지 않는다고 나오고 OtherCadetList 컴포넌트에서 자체적으로 데이터를 받아오고 있네요. 중복된 코드이므로 getOthers 함수까지 포함해서 삭제하는 편이 나을 것 같습니다.

2022-06-29 14:00 UTC, GulSam00 commented on src/Pages/TodoPage/MyTodoList.jsx
> +    getToDos(userId);
console.log는 풀리퀘 단에서 미리 삭제하는 편이 나을 것 같네요.

2022-06-29 14:00 UTC, GulSam00 approved these changes

2022-07-02 06:38 UTC, luckylooky2 commented on src/Pages/TodoPage/CadetListItem.jsx
> +};
styled component 문법을 적용해 수정하였습니다.

```
const ItemChecked = {
  textDecorationLine: 'line-through',
  color: 'gray',
};

const ItemNotChecked = {};

const ItemNotToday = {
  color: 'gray',
};
```

```
const ItemNotChecked = styled.span``;
const ItemChecked = styled.span`
  color: gray;
  text-decoration-line: line-through;
`;
const ItemNotToday = styled.span`
  color: gray;
`;
```

2022-07-02 06:43 UTC, luckylooky2 commented on src/Pages/TodoPage/CadetListItem.jsx
>      </span>
styled를 적용하기 위해 추가했다가 삭제하지 못했습니다. 수정했습니다!

2022-07-02 06:55 UTC, luckylooky2 commented on src/Pages/TodoPage/MyTodoList.jsx
> +    getToDos(userId);
적용했습니다!

2022-07-02 07:08 UTC, luckylooky2 commented on src/Pages/TodoPage/MyTodoList.jsx
>    const [othersToDo, setOthersToDo] = useState([]);
수정했습니다.

2022-07-02 07:26 UTC, luckylooky2 commented
@GulSam00 @mike2ox 피드백 수정했습니다!

2022-07-04 04:37 UTC, mike2ox requested changes

2022-07-04 04:37 UTC, mike2ox commented on src/Pages/TodoPage/CancelButton.jsx
> +    >
해당 파일 내 함수명과 setIsEdit의 전달인자를 고려해봤을 때 chanhyle님이 올리신 방법이 맞다고 봅니다.

1. CancelButton -> 특정 값들을 다 초기화 해주는 함수
2. isEdit이라는 변수값을 CancelButton이 눌렀을 때 초기화 해줘야하므로 전달인자로 `''`가 넘어가야함
3. 전달인자가 필요한 이벤트이기 때문에 익명함수형태(현재 변경하시려는 방법)로 전달하면 의도한 동작이 이뤄짐

2022-07-04 04:37 UTC, mike2ox commented on src/Pages/TodoPage/MyTodoList.jsx
>    const [isEdit, setIsEdit] = useState();
초기화 해주는게 좋아보입니다. 0이든 null이든

2022-07-04 04:37 UTC, mike2ox commented on src/Pages/TodoPage/TodoOtherList.jsx
> +          <TodoCadetName key={index}>{item.userName}</TodoCadetName>
뭔가 변경됐길래 찾아봤는데 기존에는 component로 새로 빼셨던데 그걸 없애고 간소화하셨더군요. 좋아요 😃

2022-07-04 05:29 UTC, luckylooky2 commented on src/Pages/TodoPage/CancelButton.jsx
> +    >
setIsEdit('')으로 수정했습니다.

2022-07-15 11:02 UTC, mike2ox approved these changes
고생하셨습니다 :)

2022-07-15 11:26 UTC, merged